dist: xenial

before_install:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod u+x ./rebar3

language: erlang

otp_release:
    - 21.1.4
    - 21.2.7
    - 21.3.8.1
    - 22.0.7
    - 22.1.8

install: "true"

script:
    - ./rebar3 compile
    - ./rebar3 do xref, ct
    - (./rebar3 as test do coveralls send || /bin/true)
